vapor/toolbox

vapor.swift
Using `remote show` instead of `remote get-url`.
`get-url` was [introduced](https://github.com/git/git/blob/master/Documentation/RelNotes/2.7.0.txt) in git 2.7, which makes `vapor heroku init` fail on vanilla git installed on Mac OSX el capitan (mine was 2.6.1).
Note: I couldn't find when `remote show` was added to git, but its before [git 1.5 ](https://github.com/git/git/blob/c2c5f6b1e479f2c38e0e01345350620944e3527f/Documentation/RelNotes/1.5.1.txt) (Sep 2010)
=> Using `git remote show` instead of `git remote get-url`

Sources/VaporToolbox/Build.swift
When I was trying to debug on the test server I got tired of constantly having to type `-Xswiftc -g` and added the `--debug` flag to my local copy and it seemed like this may be useful for others.
I'm also considering making a new command called `debug` that will be a little like `run` except it will setup the executable in lldb, instead of running it. What are your thoughts?
=> Added --debug flag for debug symbols.

Sources/Executable/main.swift, Sources/VaporToolbox/Build.swift, Sources/VaporToolbox/Xcode.swift, Tests/VaporToolboxTests/BuildTests.swift
This has the potential to greatly reduce build times on the command line by dynamically adding and removing a module map for `CLibreSSL`
=> dynamic modulemap

Dockerfile
Hi.
Currently `vapor docker build` fails to build any images due to Dockerfile being outdated. This PR fixes this.
=> Updates from original Dockerfile for Swift 3.0

Sources/VaporToolbox/SelfInstall.swift
I had tried to install Vapor Toolbox immediately after doing a fresh install of Sierra and it failed due to /usr/local/bin not existing yet.
=> create /usr/local/bin if it does not already exist

Sources/VaporToolbox/New.swift
The trick used to verify URLs with cURL will return the expected result and a non-success exit code. In our use case, this result is considered a "successful" execution, but the backgroundExecute function see's the non-success code and throws an error. A better, more long term approach would be an overload that ignores exit codes, but I'm not sure how doable that is.
Sources:
```
Bretts-MacBook-Pro:toolbox bretttoomey$ curl -o /dev/null --silent --head --write-out '%{http_code}\n' nodes-vapor/template
000
Bretts-MacBook-Pro:toolbox bretttoomey$ echo $?
6
```
Then, on the [libcurl website](https://curl.haxx.se/libcurl/c/libcurl-errors.html):
```
CURLE_COULDNT_RESOLVE_HOST (6)
Couldn't resolve host. The given remote host was not resolved.
```
=> Fixed cURL URL validation

Sources/VaporToolbox/HerokuPush.swift
Changed minor syntax mistake when calling `execute`.
Passed the arguments to the right place in the method
=> Fixing #108 vapor heroku push fails

Sources/VaporToolbox/Run.swift, Tests/VaporToolboxTests/RunTests.swift
This PR resolves #129 by using proper JSON parsing instead of just splitting the output of `swift package dump-package`.
As an added bonus, the Run command is now covered by tests, as much as the current implementation details support it.
=> Run: fix package name parsing in projects with targets

Sources/VaporToolbox/New.swift
(This is #122 moved under the vapor organization.)
Currently the `new` command performs a deep clone of the template repository's master branch, wasting megabytes for the complete history that is deleted on the next step.
This PR adds an extra `--depth=1` argument to `git clone` to only download the latest state.
=> New: perform shallow Git clone to avoid downloading history

Sources/Executable/main.swift, bootstrap.sh
This PR enhances the installer script to overwrite the hardcoded version in `Executable/main.swift` with the current Git tag description, i.e. the actual version number.
This resolves #126 and prevents any future confusion about the Toolbox. See the extended description in the commits for some extra explanation.
=> bootstrap.sh: use the real version number instead of hardcoding "current"

Sources/Executable/main.swift, Sources/VaporToolbox/Project.swift
- adds `vapor --version` support
- fixes https://github.com/vapor/toolbox/issues/173
=> version fixes

Sources/VaporToolbox/New.swift
This allows you to generate a project with the web template with a built-in flag instead of using the URL with the `template` flag.
vapor new project --web
=> Added --web flag for generating project

Sources/VaporToolbox/HerokuInit.swift
This PR contains 2 tiny changes:
- workDir is no longer set in the Procfile (as it’s not needed since the cwd fix) and port is correctly set instead of the v1 config parameter;
- the buildpack is pulled in explicitly from the vapor-community organization (although it was still working thanks to GH’s redirection).
=> Update heroku init for the current status quo

Sources/VaporToolbox/Xcode.swift
Permits the usage of the `-n` flag to explicitly refuse opening the Xcode project after generating it, to match the `-y` flag for explicit approval.
This could (and probably should?) be merged into `beta` branch too.
Classing as bug because the `-n` flag is already implemented but being incorrectly blocked.
=> Add "n" to excluded arguments for the `xcode` command

Sources/VaporToolbox/Build.swift, Sources/VaporToolbox/Fetch.swift, Sources/VaporToolbox/Xcode.swift, Tests/VaporToolboxTests/BuildTests.swift
This option was removed in the SPM shipped with Swift 4.1 and is not critical in previous versions.
=> Remove --enable-prefetching argument from SPM invocations.

Sources/Cloud/Commands/CloudGitHash.swift, Sources/Cloud/Commands/Group.swift, Sources/Cloud/Redis.swift
Adding feature to get git hash from Vapor Cloud replicas.
e.g.:
```
vapor cloud git-hash
```
=> Adding git hash feature for Cloud

Sources/Cloud/Commands/Configs/ConfigModify.swift
This bug meant that it was necessary to add two random arguments when modifying key-value pairs.
Instead of this being correct: vapor cloud config modify FOO=BAR HELLO=WORLD
This was necessary: vapor cloud config modify random arguments FOO=BAR HELLO=WORLD
=> Fix bug where arguments are dropped incorrectly

README.md, Sources/VaporToolbox/Build.swift, Sources/VaporToolbox/Test.swift
If we tag another release, let's make this small change to remove "Slack" from two messages.
Nothing urgent.
=> Changing Slack

Sources/Executable/main.swift
Since CommandError is now an enum, we need to change all consumers of console-kit.
Also, shouldn't we pin the dependencies for the homebrew build? It seems it is using the latest of everything at the moment, and that might break easily.
=> Update error output for CommandError as enum

Sources/VaporToolbox/Update.swift
So I was getting a bit bored of explaining how to use `swift package update` instead of `vapor update` when things go south. This PR removes the offending function from the code, thus fixes #234 and fixes #215.
=> Remove harmful checkGitUpstream call from Update

Sources/VaporToolbox/XcodeCommand.swift
=> Fixed issue where Package.swift was misspelled in the xcode command

Package.resolved, Sources/VaporToolbox/Clean.swift, Sources/VaporToolbox/New/New.swift, Sources/VaporToolbox/New/TemplateScaffolder.swift, Sources/VaporToolbox/Shell.swift, Sources/VaporToolbox/Supervisor/SupervisorInit.swift, Sources/VaporToolbox/Utilities.swift, Sources/VaporToolbox/Xcode/Xcode.swift
- All executed shell commands now properly escape their arguments.
- Use of shell execution has been replaced with use of `FileManager` in most places.
- `vapor new` now has a `-T/--template` option which allows specifying a template repository to clone.
- `vapor new` now has a `-o/--outputDirectory` option which allows specifying where and with what name the new project directory is created. The directory name does _NOT_ have to match the project name, though it is recommended.
- `vapor clean` no longer has a `-k/--keep-checkouts` option, as it did not usefully perform as advertised.
- Update to NIO 2.15
- Project paths and names may now contain spaces and special characters, though names in particular should be kept as simple as possible.
=> Add shell escaping, use FileManager where possible, add new options to vapor new, cleanup of vapor clean

Sources/VaporToolbox/Build.swift, Sources/VaporToolbox/Run.swift
This mainly includes:
> Add `--enable-test-discovery` flag as default
While also fixed:
> Fix hard-coded Swift path
=> Fix issues with Swift 5.2 on Ubuntu

Dockerfile
`docker build` doesn't work anymore due to swift 5.2 being required, so i updated the Dockerfile to 5.2.
=> update Dockerfile to 5.2

Sources/VaporToolbox/exec.swift
There is an error when building toolbox-18.0.0-beta.28 on raspberry pi 4 Ubuntu 20.04 Swift 5.2.3
/home/ubuntu/toolbox-18.0.0-beta.28/Sources/VaporToolbox/exec.swift:36:42: error: value of optional type 'UnsafeMutablePointer<Int8>?' must be unwrapped to a value of type 'UnsafeMutablePointer<Int8>'
let spawned = posix_spawnp(&pid, argv[0], &fileActions, nil, argv + [nil], envp + [nil])
Using compactMap to fix issue described above
----------------------------------------------------
There is an error when running command 'vapor-beta run' on raspberry pi 4 Ubuntu 20.04 Swift 5.2.3 
Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file /home/ubuntu/toolbox-18.0.0-beta.28/Sources/VaporToolbox/exec.swift, line 13
Using '#if os(Linux)' and …
=> Fix for Ubuntu 20.04 raspberry pi 4

Sources/VaporToolbox/boot.swift
=> Add better error message for use of removed `vapor update` command

Sources/VaporToolbox/boot.swift
Adds a global `--version` flag for printing framework and toolbox version. 
```sh
$ vapor --version
framework: 4.15.2
toolbox: 18.1.0
```
=> Add --version flag

Sources/VaporToolbox/Run.swift
`vapor run` now correctly forwards the confirm override flag (`--yes` or `--no`) to the app (#333, fixes #332).
=> Forward confirm override

Makefile, Sources/VaporToolbox/Toolbox.swift, Sources/VaporToolbox/Version.swift, scripts/current-version.sh, scripts/current-version.swift
Adds a Makefile with `build`, `install`, and `uninstall` commands (#339, fixes #338)
Using `make build` will attempt to infer the current toolbox version number and compile it into the executable for lookup via `--version`. 
Sample output:
```
$ vapor --version
framework: 4.27.1
toolbox: tn-version-number (90e3d12)
```
=> Add Makefile + optional static version

Makefile
Adds `sudo` to the lines `mv .build/release/vapor ${DEST}` and `rm ${DEST}`, since root level permissions are required to make changes to `$DEST` (/usr/local/bin). (Note that simply running `sudo make install` without this change will result in errors.) Also added a line to change the permissions of the build moved into `/usr/local/bin` to match with standard conventions.
Possibly fixes issue #347, but not enough detail is noted in said issue to know if it's the same problem.
=> Makefile permissions issue fix

.github/workflows/test.yml, Sources/VaporToolbox/New/TemplateScaffolder.swift
- Simple boolean flags in the template, such as `--leaf`, now work, and have negating forms, e.g. `--no-leaf`. Complex nested variables such as `--fluent` now also have a negating form. The intent is that automation is no longer limited to the catch-all `--yes` or `--no` overrides and thus can express non-trivial configurations such as "Leaf but not Fluent". (Note: This was not a significant issue until the template manifest started asking more than one yes/no question per invocation, but with the addition of Leaf support pending in vapor/template#44, such is now the case.)
- `.bool` variables specified in a manifest are now only defined in the resulting context if they would have the value `true`. This fixes `if: someboolvar` always being treated as `true` regardless of its actual value …
=> Fix several inconsistencies in template handling of arguments and inputs

Sources/VaporToolbox/New/New.swift
When we try to create a new app with the toolbox in the code we fallback to a default branch name 'master', however it is now changed to 'main'. This change merely fixes that issue.
=> Fix incorrect default branch name 

Sources/VaporToolbox/New/TemplateScaffolder.swift
This adds support for `kebab_names` in templates to avoid issues where certain contexts require lowercase variables (such as Docker compose).
Fixes #334
=> Add Kebab case support to TemplateScaffolder context

.github/workflows/test.yml
Got rid of the getcidata
Created a json task for 
`Ubuntu-latest` with image `swift:5.2-focal` and `swift:5.5-focal`
`macos-11` with toolchain `latest`
Update the workflow to test for the swift 5.5 release
If all tests pass then it should it should close #374
=> Bug/update ci Update CI to run with swift 5.5 only

Sources/VaporToolbox/Toolbox.swift
When using _vapor --version_, the output in a non vapor directory would be
```bash
```
This pr changes those framework and note texts to:
```bash
```
in projects that have no Package.resolved.
in projects that do have a Package.resolved but that aren't Vapor projects it changes the framework text to:
```bash
```
closes #345
=> Improve the messaging for the version command

Sources/VaporToolbox/New/New.swift
Changed the instruction to use "vapor xcode" to instead be "open Package.swift", as is described in Vapor 4 docs
=> Changing info screen to instruct user to open Package.swift

Sources/VaporToolbox/Build.swift, Sources/VaporToolbox/Run.swift, Sources/VaporToolbox/Utilities.swift, Tests/VaporToolboxTests/VaporToolboxTests.swift
Removing this flag fixes a warning which appears every time an app is built or run through the toolbox.
```shell
vapor build
```
Output:
```shell
Building project...
warning: '--enable-test-discovery' option is deprecated; tests are automatically discovered on all platforms
```
The `--enable-test-discovery` flag is not needed anymore as deprecated because now it is the default behaviour.
=> Removed deprecated --enable-test-discovery flag from build and run commands

Package.swift
[Manually building](https://github.com/Homebrew/homebrew-core/blob/b7824316b8c6d4488c5b84a758b15d02a9e99e12/Formula/vapor.rb#L20-L21) `toolbox-18.3.5` on macOS logs the following compiler warnings:
```
Working copy of https://github.com/jpsim/Yams.git resolved at 2.0.0
/Users/daniel/Downloads/toolbox-18.3.5/.build/checkouts/Yams/Sources/Yams/Emitter.swift:338:32: warning: initialization of 'UnsafeMutablePointer<yaml_version_directive_t>' (aka 'UnsafeMutablePointer<yaml_version_directive_s>') results in a dangling pointer
versionDirective = UnsafeMutablePointer(&versionDirectiveValue)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/daniel/Downloads/toolbox-18.3.5/.build/checkouts/Yams/Sources/Yams/Emitter.swift:338:53: note: implicit argument conversion from 'yaml_version_directive_t' …
```
=> Update Yams dependency to "from: 4.0.0"

Sources/VaporToolbox/Heroku/HerokuInit.swift
Running `vapor heroku init`, and choosing to use the buildpack (vs docker), creates a Procfile with the following:
```
web: Run serve --env production --hostname 0.0.0.0 --port \$PORT
```
This works okay when deployed to heroku (note the `--port \4386`):
```
2022-03-08T07:07:33.775125+00:00 heroku[web.1]: Starting process with command `Run serve --env production --hostname 0.0.0.0 --port \4386`
2022-03-08T07:07:35.820116+00:00 app[web.1]: [ NOTICE ] Server starting on http://0.0.0.0:4386
```
However, it doesn't work when using the `heroku local` command:
```
$ heroku local
10:54:26 PM web.1 |  [1/1] Planning build
10:54:31 PM web.1 |  [0/0] Build complete!
10:54:31 PM web.1 |  [ WARNING ] Could not convert option for `port` to Int
10:54:31 PM web.1 |  Swift/ErrorType.swift:200: Fatal …
```
=> Remove backslash from Procfile created by `vapor heroku init`

Sources/VaporToolbox/New/New.swift
This change allows users to create a project without automatically creating a Git repository in the new folder. This can be helpful when creating the project inside another project already using Git.
To use the new feature, add `--no-git` to the `vapor new` command.
=> Allow not adding a Git repo when creating a new project

Makefile
Sudo is not available in containers, running sudo breaks `make install`. Solve the issue by checking whether the user is root, and if he is, no need to use sudo.
I recommend more testing before merging
=> Compatibility with official swift container images

scripts/build.swift
Changed the build script to use the new `Task` API as described in issue [#392](https://github.com/vapor/toolbox/issues/392)
=> Use new API for build script

.github/workflows/test.yml, Dockerfile, Package.swift, scripts/build.swift
This removes support for Swift 5.2 and Swift 5.3, making Swift 5.4 the earliest supported version [as announced](https://blog.vapor.codes/posts/vapor-swift-versions-update/)
=> Update Supported Swift Versions

.github/workflows/test.yml, .gitignore, Package.swift, Sources/VaporToolbox/Build.swift, Sources/VaporToolbox/Clean.swift, Sources/VaporToolbox/Heroku/HerokuInit.swift, Sources/VaporToolbox/Heroku/HerokuPush.swift, Sources/VaporToolbox/Run.swift, Sources/VaporToolbox/Supervisor/SupervisorInit.swift, Sources/VaporToolbox/Supervisor/SupervisorRestart.swift, Sources/VaporToolbox/Supervisor/SupervisorUpdate.swift, Sources/VaporToolbox/Xcode/Xcode.swift
* Bumps the minimum required Swift version to 5.6 to match SwiftNIO
* Adds deprecation warnings to all the old commands
* Handle the new Vapor templates with a different executable name (you should still use `swift run` anyway)
=> Update Toolbox for new Templates

Package.resolved, Package.swift
This fixes building the toolbox on Arch Linux and uses a much newer version of the `mustach` parser for good measure.
=> Use the new updated Mustache package from vapor-community

.github/workflows/test.yml, Package.swift
Bumps the integration tests to 5.10 to match the template and the toolbox minimum Swift version to 5.8 to match Vapor
=> Update Swift Versions

Sources/VaporToolbox/TemplateRenderer.swift, Tests/VaporToolboxTests/VaporToolboxTests.swift
Fixes issue related to https://github.com/vapor/template/pull/152
The name sanitization is very opinionated, let me know what you think
=> Sanitize the project name if it is invalid to use for Swift targets, files or types
