vapor

http://swiftlang.ng.bluemix.net/#/repl/e0e1fa62e9534ec86d021cfbf7931faa82b0ce967d1d3199706a589c3aa2aff1

Fixed #5: Bug in trimmedSpaces

---

vapor

- Added ASCII art when “vapor help” and "vapor new" executed
- Renamed Error to RunError, added Error for general errors
- Added runWithOutput to be able to run commands and get the return
value from it
- Added ability to specify the type of character to trim, renamed
trimmedSpaces to trim, move it to the beginning of the file
- Added terminalSize() used to find the number of columns and lines in
the terminal
- Added ANSIColor which lists the types of colors available and their
color codes
- Added centerBlockText for centering blocks of text

Added ASCII art

---

Dockerfile

Docker build less verbose

---

.travis.yml
vapor.swift

Fixes #19 
I've set the version to 0.1 for now

Added version command

---

Dockerfile

Refer this https://github.com/vapor/toolbox/issues/83 for more information

curl tool is added to fix missing libcurl.so

---

Sources/VaporToolbox/HerokuInit.swift

This PR adds ability to create Heroku app to other regions than "us" (Heroku default)

Added ability to choose deployment region for new Heroku apps

---

Sources/VaporToolbox/HerokuInit.swift

Fix incorrect heroku CLI invocation with the region string

---

Sources/Executable/main.swift
Sources/VaporToolbox/Build.swift
Sources/VaporToolbox/File.swift
Sources/VaporToolbox/Xcode.swift

slight cleanup and adding update command

---

Sources/VaporToolbox/New.swift

Update New.swift with auth template

---

Sources/VaporToolbox/HerokuInit.swift

Fixed grammatical error in HerokuInit tool.

---

Sources/Cloud/CloudAPI/Cloud+Application.swift
Sources/Cloud/CloudAPI/Cloud+Project.swift
Sources/Cloud/CloudAPI/TokenCache.swift
Sources/Cloud/Commands/Create/CreateApplication.swift
Sources/Cloud/Commands/Create/CreateDatabase.swift
Sources/Cloud/Commands/Create/CreateEnvironment.swift
Sources/Cloud/Commands/Create/CreateHosting.swift
Sources/Cloud/Commands/Create/CreateProject.swift
Sources/Cloud/Commands/Deploy.swift
Sources/Cloud/Commands/Login.swift
Sources/VaporToolbox/New.swift
vapor.json

Improves the `vapor cloud deploy` process:
Updated docs: https://github.com/vapor-cloud/documentation/pull/11

vapor cloud deploy updates

---

Sources/Cloud/Commands/Database/DatabaseDelete.swift
Sources/Cloud/Commands/Database/DatabaseFeedbackFormat.swift
Sources/Cloud/Commands/Database/DatabaseInspect.swift
Sources/Cloud/Commands/Database/DatabaseLogSubscribe.swift
Sources/Cloud/Commands/Database/DatabaseLogin.swift
Sources/Cloud/Commands/Database/DatabaseResize.swift
Sources/Cloud/Commands/Database/DatabaseRestart.swift
Sources/Cloud/Commands/Database/DatabaseShutdown.swift
Sources/Cloud/Commands/Database/ShowDatabaseInfo.swift
Sources/Cloud/Redis.swift

Adding loaders on db features

---

Sources/Cloud/ApplicationApi.swift
Sources/Cloud/Commands/Beta/GroupBeta.swift
Sources/Cloud/Commands/Beta/Resize.swift
Sources/Cloud/Commands/Beta/Restart.swift
Sources/Cloud/Commands/Beta/S3.swift
Sources/Cloud/Commands/Beta/Scale.swift
Sources/Cloud/Commands/Database/DatabaseLogSubscribe.swift
Sources/Cloud/Globals.swift
Sources/Cloud/Redis.swift
Sources/Executable/main.swift

Adding support for Resize and Scale deployment types in cloud-beta

Starting building Cloud beta

---

Sources/Executable/main.swift

Using the Discord link from the vapor-3-0-0-released post here:  https://medium.com/@codevapor/vapor-3-0-0-released-8356fa619a5d
Not 100% sure that's the best one to use here but it's the only published one I could find.

Update to reflect move of team chat to Discord

---

Package.swift

This minor version fixes problem with new Organization resolver
@tanner0101 let's get this in asap :) (Before next release)

Forcing Cloud clients to minor 22

---

Package.swift
vapor.rb

This adds support to Mint #274

Add an executable product 'vapor' to Package.swift

---

Sources/CloudCommands/CloudGroup.swift
Sources/CloudCommands/Deploy.swift
Sources/CloudCommands/Git/RemoteGroup.swift
Sources/CloudCommands/SSH/SSHAdd.swift
Sources/CloudCommands/UserCommands/Login.swift
Sources/CloudCommands/UserCommands/ResetPassword.swift
Sources/CloudCommands/UserCommands/Signup.swift
Sources/VaporToolbox/New.swift

- Changed all command-line Options to optionals
for compatibility with vapor/console-kit#125
Fixes #288
Fixes vapor/console-kit#128
Refs vapor/homebrew-tap#26

Option propertywrapper options are optional

---

Sources/Executable/main.swift
Sources/VaporToolbox/Build.swift
Sources/VaporToolbox/Clean.swift
Sources/VaporToolbox/Heroku/Heroku.swift
Sources/VaporToolbox/Heroku/HerokuInit.swift
Sources/VaporToolbox/Heroku/HerokuPush.swift
Sources/VaporToolbox/New/New.swift
Sources/VaporToolbox/New/TemplateScaffolder.swift
Sources/VaporToolbox/Process+Git.swift
Sources/VaporToolbox/Process+Heroku.swift
Sources/VaporToolbox/Process+Swift.swift
Sources/VaporToolbox/Run.swift
Sources/VaporToolbox/Shell.swift
Sources/VaporToolbox/Supervisor/SupervisorInit.swift
Sources/VaporToolbox/Supervisor/SupervisorRestart.swift
Sources/VaporToolbox/Supervisor/SupervisorUpdate.swift
Sources/VaporToolbox/Utilities.swift
Sources/VaporToolbox/Xcode/Xcode.swift
Sources/VaporToolbox/Xcode/XcodeBuild.swift

Adds Docker support to `vapor heroku init`.
Adds `vapor heroku push` command.

Improve Heroku Init + Add Heroku Push

---

Sources/VaporToolbox/Build.swift
Sources/VaporToolbox/Heroku/HerokuInit.swift
Sources/VaporToolbox/Heroku/HerokuPush.swift
Sources/VaporToolbox/Process+Run.swift
Sources/VaporToolbox/Run.swift
Sources/VaporToolbox/boot.swift
Sources/VaporToolbox/exec.swift

Fixes a bug causing stdin to not be passed to commands like `vapor run`.

Fix Vapor Run

---

.github/FUNDING.yml
.github/workflows/test.yml
Package.resolved
Package.swift

Updates to Swift 5.2 + adds CI for verifying Linux builds (#304, fixes #304).

Update to 5.2 + test CI

---

.github/workflows/test.yml

We don't need anything from brew now

---

Sources/VaporToolbox/Run.swift

Also add an explanatory line to the output with the equivalent swift package manager command.
Fixes #341

Don't try to build the app when using only the `-h` or `--help` flags on the `run` command

---

Sources/VaporToolbox/Toolbox.swift

Fixes issue when trying to decode V2 Package.resolved files

Fix Package.resolved version decoding issue

---

Sources/VaporToolbox/Toolbox.swift

- Add Package.resolved v2 decoding support
- Align PackageResolvedV1 definition with [swift-package-manager](https://github.com/apple/swift-package-manager)

Add support for Package.resolved v2

---

Dockerfile

Add the required CA certificates for git to fetch the Vapor template from GitHub
Add the required git configurations for git to create the first commit

#404 - Add certificates for Docker on Linux

---

Package.swift

We need to support 5.5 for Homebrew

Backport support for Swift 5.5

---

.github/workflows/test.yml

More CI cleanup

---

Package.swift
README.md
Sources/VaporToolbox/TemplateManifest.swift
Sources/VaporToolbox/Vapor.swift
Tests/VaporToolboxTests/VaporToolboxTests.swift
Tests/VaporToolboxTests/manifest.json

While keeping YAML files as the default, add support for parsing manifest files in JSON format

Add support for JSON manifest files
